# Ch.04 Naive Bayes

## 4.5.1

In [3]:
import bayes

In [ ]:
listOPost,listClasses = bayes.loadDataSet()

In [ ]:
listOPost

In [ ]:
listClasses

In [ ]:
myVocabList = bayes.createVocabList(listOPost)

In [ ]:
myVocabList

### setOfWords2Vec

In [ ]:
bayes.setOfWords2Vec(myVocabList,listOPost[0])

### 4.5.2 단어 벡터로 확률 계산하기

In [1]:
from numpy import *

In [4]:
import imp
imp.reload(bayes)

<module 'bayes' from 'bayes.pyc'>

In [5]:
listOPosts, listClasses = bayes.loadDataSet()

In [6]:
myVocabList = bayes.createVocabList(listOPosts)

In [7]:
trainMat = []

In [8]:
for postinDoc in listOPosts:
    trainMat.append(bayes.setOfWords2Vec(myVocabList,postinDoc))

In [9]:
len(trainMat)

6

In [10]:
p0V, p1V, pAb = bayes.trainNB0(trainMat,listClasses)

In [15]:
p0V #0:폭력적이지 않은 문서들 중에서 각 단어의 등장 확률
#sum(p0V)

array([0.04166667, 0.04166667, 0.04166667, 0.        , 0.        ,
       0.04166667, 0.04166667, 0.04166667, 0.        , 0.04166667,
       0.04166667, 0.04166667, 0.04166667, 0.        , 0.        ,
       0.08333333, 0.        , 0.        , 0.04166667, 0.        ,
       0.04166667, 0.04166667, 0.        , 0.04166667, 0.04166667,
       0.04166667, 0.        , 0.04166667, 0.        , 0.04166667,
       0.04166667, 0.125     ])

In [16]:
p1V #1:폭력적인 문서 중에서 각 단어의 등장 확률
#sum(p1V)

array([0.        , 0.        , 0.        , 0.05263158, 0.05263158,
       0.        , 0.        , 0.        , 0.05263158, 0.05263158,
       0.        , 0.        , 0.        , 0.05263158, 0.05263158,
       0.05263158, 0.05263158, 0.05263158, 0.        , 0.10526316,
       0.        , 0.05263158, 0.05263158, 0.        , 0.10526316,
       0.        , 0.15789474, 0.        , 0.05263158, 0.        ,
       0.        , 0.        ])

In [12]:
pAb

0.5

In [64]:
n1=zeros(4);n1
n2=[0,0,1,0];n2

[0, 0, 1, 0]

In [65]:
n1 + n2[2]

array([1., 1., 1., 1.])

### 4.5.3: 두 가지 문제
    1. P(a|c1) 중 하나라도 0이라면 p(c1|w)의 값도 0
    2. 언더플로우
        :p(w|c1)의 값은 0과 1사이의 값인데 보통 아주 작은 값이고 이 값들이 다 곱해지면 아주 작은 값이 된다.
         
* 해결
    1. 모든 단어가 적어도 한 번은 나타났다고 가정
    2. 확률 계산시 로그 함수 적용

In [18]:
bayes.testingNB()

['love', 'my', 'dalmation'] classified as:  0
['stupid', 'garbage'] classified as:  1


### 4.5.4: Bag of Words

In [20]:
newPost = 'I Love my dalmation'
inDoc = newPost.strip().split()

In [21]:
inDoc

['I', 'Love', 'my', 'dalmation']

In [24]:
listOPosts,listClasses = bayes.loadDataSet()
myVocabList = bayes.createVocabList(listOPosts)

In [27]:
bayes.bagOfWords2VecMN(myVocabList,inDoc)

[0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [28]:
import re

In [31]:
regEx = re.compile('\\W+')

In [32]:
regEx.findall('wooo!! dhdhdhdhdh\t dhdhdhdh')

['!! ', '\t ']